from main_day_8_1 import count_antinode_positions


def test_count_antinode_positions(tmp_path):
    input_file = tmp_path / "input.txt"
    input_data = """............
                    ........0...
                    .....0......
                    .......0....
                    ....0.......
                    ......A.....
                    ............
                    ............
                    ........A...
                    .........A..
                    ............
                    ............"""
    input_file.write_text(input_data)

    result = count_antinode_positions(str(input_file))
    print(result)
    assert result == 14
